# Generated by Django 4.1.2 on 2022-11-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="index_banner",),
    ]
