# Generated by Django 4.1.2 on 2022-11-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ecomapp", "0002_delete_index_banner"),
    ]

    operations = [
        migrations.CreateModel(
            name="feature_items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="feature_items")),
                ("is_sold", models.BooleanField(default=False)),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
    ]
