# Generated by Django 4.1.2 on 2022-12-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0004_cate_blazer_cate_kids_cate_poloshirt_cate_sunglass_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="categ_adidas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="categ_adidas")),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="categ_asics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="categ_asics")),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="categ_bags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="categ_bags")),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="categ_clothing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="categ_clothing")),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="categ_fashion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="categ_fashion")),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="categ_households",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="categ_households")),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="categ_interiors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="categ_interiors")),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="categ_kids",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="categ_kids")),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="categ_men_armani",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="categ_men_armani")),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="categ_men_chanel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="categ_men_chanel")),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="categ_men_dior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="categ_men_dior")),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="categ_men_dolceandgabbana",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="categ_men_dolceandgabbana")),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="categ_men_fendi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="categ_men_fendi")),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="categ_men_gucci",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="categ_men_gucci")),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="categ_men_guess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="categ_men_guess")),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="categ_men_prada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="categ_men_prada")),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="categ_men_valentino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="categ_men_valentino")),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="categ_men_versace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="categ_men_versace")),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="categ_nike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="categ_nike")),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="categ_puma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="categ_puma")),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="categ_shoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="categ_shoes")),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="categ_underarmour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="categ_underarmour")),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="categ_women_dior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="categ_women_dior")),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="categ_women_fendi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="categ_women_fendi")),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="categ_women_guess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="categ_women_guess")),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="categ_women_valentino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="categ_women_valentino")),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="categ_women_versace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="categ_women_versace")),
                ("visible", models.BooleanField(default=False)),
            ],
        ),
    ]
