# Generated by Django 4.1.2 on 2022-12-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0005_categ_adidas_categ_asics_categ_bags_categ_clothing_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="registerCust",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("uname", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("psw", models.CharField(max_length=50)),
            ],
        ),
    ]
