# Generated by Django 4.1.2 on 2022-12-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0007_get_in_touch"),
    ]

    operations = [
        migrations.RenameModel(old_name="get_in_touch", new_name="getintouch",),
    ]
